print("Welcome to the tip calculator! ")
bill = float(input("What was the total bill? - $"))
tip = int(input("How much tip would you like to give? 10,12 or 15? - "))
people = int(input("In many people we have to spit the bill? "))
tip_bill = round((tip/100*bill + bill)/people , 2)
print( f"Each person should pay - ${tip_bill}  ")